import { QueryClient, dehydrate } from '@tanstack/react-query';
import { Metadata } from 'next';
import React from 'react';
import AppFooter from './components/AppFooter';
import AppHeader from './components/AppHeader';
import QueryProvider from './components/QueryProvider';
import { START_TIME } from './config/env';
import './global.scss';
import dashboardState from './query/dashboardState';

export const metadata: Metadata = {
  title: 'Welcome to query-impl-app',
  description: 'Generated by create-nx-workspace',
};

const init = async (queryClient: QueryClient) => {
  await dashboardState.setData(
    {
      startupTime: START_TIME.toISOString(),
      initTime: new Date().toISOString(),
    },
    queryClient
  );
};

async function RootLayout({ children }: { children: React.ReactNode }) {
  const queryClient = new QueryClient();
  await init(queryClient);
  const state = dehydrate(queryClient);

  return (
    <html lang="en">
      <body>
        <QueryProvider state={state}>
          <AppHeader />
          <main>{children}</main>
          <AppFooter />
        </QueryProvider>
      </body>
    </html>
  );
}

export default RootLayout;
