import { Metadata } from 'next';
import { PropsWithChildren } from 'react';
import AppFooter from './components/AppFooter';
import AppHeader from './components/AppHeader';
import QueryProvider from './components/QueryProvider';
import './global.scss';
import 'react-loading-skeleton/dist/skeleton.css';

export const metadata: Metadata = {
  title: 'Welcome to query-impl-app',
  description: 'Generated by create-nx-workspace',
};

async function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <AppHeader />
          <main>{children}</main>
          <AppFooter />
        </QueryProvider>
      </body>
    </html>
  );
}

export default RootLayout;
